export const botonesObj=[
    {
        id:'alive',
        status:'Alive',
        type:'status'
    },
    {
        id:'dead',
        status:'Dead',
        type:'status'
    },
    {
        id:'femaleOption',
        status:'Female',
        type:'gender'
    },
    {
        id:'MaleOption',
        status:'Male',
        type:'gender'
    },
    {
        id:'unknownOption',
        status:'unknown',
        type:'gender'
    },
    {
        id:'humanOption',
        status:'Human',
        type:'species'
    },
    {
        id:'alienOption',
        status:'Alien',
        type:'species'

    },
    {
        id:'humanoidOption',
        status:'Humanoid',
        type:'species'

    },
    {
        id:'unknowOption',
        status:'unknown',
        type:'species'
    },
    {
        id:'mythologyOption',
        status:'Mytholog',
        type:'species'
    },
    {
        id:'animalOption',
        status:'Animal',
        type:'species'
    },
    {
        id:'vampireOption',
        status:'Vampire',
        type:'species'
    },
    {
        id:'robotOption',
        status:'Robot',
        type:'species'
    },
    {
        id:'cronenbergOption',
        status:'Cronenberg',
        type:'species'
    },
    {
        id:'diseasseOption',
        status:'Disease',
        type:'species'
    },
    {
        id:'parasiteOption',
        status:'Parasite',
        type:'species'
    },        
]